Align krell repl initialization to latest version (#3014)
As found in https://github.com/vouch-opensource/krell/wiki/Tooling-Integration---Emacs%2C-Cursive%2C-VSCode-etc.

The current initialization code causes an exception to be raised when
jacking-in:
   
ReferenceError: Can't find variable: cljs